### ISSUE TITLE
【ラボ2】Cloud9上で「npm start」を実行すると異常終了する。

### ISSUE THREAD

**Issue by touchez-du-bois** [harunobukameda/AWS-Amplify-AWS-Lambda-Amazon-DynamoDB-AWS-API-Gateway-Amazon-Cognito#1]
# 現象
「5. ラボ2」で、Cloud9上で「npm start」を実行すると異常終了します。エラーメッセージは次のとおりです:
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/ec2-user/environment/20211103amplify/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ec2-user/environment/20211103amplify/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/ec2-user/environment/20211103amplify/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/ec2-user/environment/20211103amplify/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/ec2-user/environment/20211103amplify/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/ec2-user/environment/20211103amplify/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/ec2-user/environment/20211103amplify/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/ec2-user/environment/20211103amplify/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
```

# 環境
実行環境等は次のとおりです:
- 2021年11月3日
- Chrome 95.0
- Cloud9
- Node.jsのバージョン: v17.0.1
- npmのバージョン: 8.1.0

# 原因
Node.jsがv17でOpenSSL v3.0をサポートするようになったが、OpenSSL v3.0でデフォルトで許可されなくなったアルゴリズムやキーサイズ等をアプリケーションやモジュールが使用しようとしているのが原因と考えられます。
詳細は[ここ](https://nodejs.org/en/blog/release/v17.0.0/#openssl-3-0)を参照願います。

# 対処
環境変数を設定して一時的に回避する方法と、package.jsonを変更して一時的に回避する方法があるようです。
## 環境変数を設定する
Cloud9のターミナル上で、
```
export NODE_OPTIONS=--openssl-legacy-provider
```
と一時的に「レガシープロバイダーへ戻す」環境変数を設定し、その後
```
npm start
```
を実行します。あるいは、毎回
```
NODE_OPTIONS=--openssl-legacy-provider npm start
```
と環境変数を指定して実行します。
## package.jsonを変更する
Cloud9で「YYYYMMDDamplify/package.json」ファイルを開き、15行目を
```
"start": "react-scripts start",
```
から
```
"start": "react-scripts --openssl-legacy-provider start",
```
のように変更し保存します。その後、
```
npm start
```
を実行します。

**Comment by harunobukameda** [comment]
ありがとうございます。ご提案いただいた方法の1でいきますね。

**Comment by harunobukameda** [comment]
修正版Upしました！
